### ISSUE TITLE
Data Base Structure

### ISSUE THREAD

**Issue by leninchek** [samcfinan/Angular-4-Material-POS#1]
Hi,

I installed the project and run.

I want to try it locally but I need the data base structure.

Can you help me?

Thanks.

**Comment by samcfinan** [comment]
Hi there,

The database is hosted on my Firebase project. You'll have to create a Firebase project and initialize a database yourself. I'm planning on providing instructions on how to do that within the next couple of days. At this point, this project is just a demo, unfortunately

Best,
Sam
