### ISSUE TITLE
Error when setting up

### ISSUE THREAD

**Issue by HarrisonMayotte** [samcfinan/Angular-4-Material-POS#3]
Hi there. When setting up the POS on my domain, I am getting this error in the console and guest + password reset is not working. Also, how would I go about creating a user on there before my own admin is created (like creating my own user)?
![image](https://user-images.githubusercontent.com/48367813/58121179-c763cb00-7bd4-11e9-8723-b640f0eab69d.png)

**Comment by HMayotte** [comment]
Any Update?
